# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

lbel.conx=Connection
lbel.ident=ID
lbel.uzer=User
lbel.pswd=Password
lbel.forget_pswd=Forgot password?
lbel.newaccount=Create new account
chbx.showpswd=Show password
lbel.or_=or
lbel.help = Need help ?
lbel.slogan=Your business at a safe place
txtfield.prompt.ident=Company identification
txtfield.prompt.uzer=User phone (+243xxx)
txtfield.prompt.pswd=Password
xgen_order=Generate order
xprix_achat=Purchase price
xmaincarency=Main currency
xwarn_cli=Warning message : 

#main
xtxtfield.prompt.rechr=Search
xlbel.curen_tview=Dashboard
xtooltip.prodwi=Products & Services
xtooltip.fina_nce=Cash flow
xtooltip.entr_epot=Warehouses
xtooltip.vent_erecq=Sales & Requisitions
xtooltip.ag_ents=Manage Agents
xtooltip.rap_poro=Reports
xtooltip.com_panie=Company
xtooltip.newdelivery=Receive new delivery
xtooltip.newsupplier=Create new supplier
xtooltip.newitems=Add items
xaddingitem=Add articles
xtooltip.param_ettre=Settings
xlbel.loading=Loading...
xtooltip.hel_p=Open manual
xtooltip.fer_me=Close
xtooltip.redu_ire=Reduce
xtooltip.agran_dir=Enlarge
xlbel.depense_proport=Expense (%s%s) average %s USD
xgraph.ti_tre=Metrics
xstock.empty=Out of Stock
xlblstk.inrupt=Products out of stock
xlastdate=Last date
xremainingstock=Remaining stock
xgraph.seri1_vente=Sales
xgraph.seri2_depens=Respend cost
xgraph.seri3_marg=Result
xmwezi_1=January
xmwezi_2=February
xmwezi_3=March
xmwezi_4=April
xmwezi_5=May
xmwezi_6=June
xmwezi_7=July
xmwezi_8=August
xmwezi_9=September
xmwezi_10=October
xmwezi_11=November
xmwezi_12=December
xpie.ti_tre=Popular product
xlbel.ver_sion=Version
xlbel.majdispo=Update available
xlbel.cre_ance=Credit volume
xlbel.tod_ay=Today

#Products
xlbel.produx=Products
xbtn.ajou_ter_produit=Add a product
xlink.tlcharger_xls=Download the sample .xls file
xpas_de_selection=No selection
xall_category=All categories
xall=Select all
xcol.code_bar=Bar-code
xcol.nom_produit=Product name
xcol.mark=mark
xcol.modele=Model/Shape
xcol.tail=Size/Focus
xflow=Color
xaction=Actions
xmes_ure=Measures
xnon_mes_ure=No measurement
xadd_mes_ure=Add a measurement
xbtn.update=Edit
selectdeliv=Select deliveries
updateliv=Edit delivery
xligne_par_pg=Line per page
xitems=%s Items
xtooltip.print_cb=Print bar-code
xtooltip.import_xls=Import products from an excel file
xtooltip.refresh=Refresh data
xtooltip.update=Edit a selected element
xtooltip.delete=Delete a selected element
xtooltip.import_gros=Import products with wholesale and retail prices from Excel
xtooltip.import_detail=Import products with detailed prices
xtooltip.refresh=Refresh data
xlbl.new_prod=New product
xlbl.categorie=Category
xchoose_category=Choose a category
xtooltip.browse=Choose an image from my computer
xtooltip.search=Search image on Google
xtxtf.prompt.cbar=Product bar-code or number
xtxtf.prompt.nomp=Product name
xtxtf.prompt.mark=Mark
xtxtf.prompt.model=Model/Shape
xtxtf.prompt.tail=Size/focus(optional)
xtxtf.prompt.color=Color (optional)
xcbx.prompt.descrim=Measurement description
xcbx.prompt.unit_m=Number of units in the measurement
xbtn.cancel=Cancel
xbtn.save=Save
xcbx.sample.pc=Piece
xcbx.sample.meter=Meter
xcbx.sample.tour=Tour
xcbx.sample.hour=Time
xcbx.sample.bouteil=Bottle
xcbx.sample.kg=Kg
xcbx.sample.plqt=Plaquette
xcbx.sample.plat=Plat
xcbx.sample.night=night
xlbl.mes_ure_prosel=Measurements for the selected product
xtxtf.prompt.descr=Description
txtf.prompt.qteum=Number of units in the measurement
xbtn.add_mes_ure=Add measurement
xbtn.ok=OK
xbtn.yes=YES
xbtn.no=NO
xbtn.next=Next >
xsite_destinat=Recipient site
xsto_ckage_only=Storage only
ximport_in_progress=Import in progress...
xbtn.close=Close

#Traisoreirie
xlbl.treso_rerie=Treasury
xlbl.cais_se=Cash
xlbl.recov=Recoveries
xlbl.depense=Expenses
xlbl.ecriture=Transactions
xreference=Reference
xlbl.encaiss=Cash
xlbl.decaiss=Disbursement
xstatut=Status
xbtn.mark_as_sold=Mark as sold
xtxtf.prompt.montant_usd=USD amount
xtxtf.prompt.montant_cdf=CDF amount
xtxtf.prompt.motif_trans=Transaction reason
xtxtf.prompt.observation=Observation (optional)
xcol.observation=Observation
xregions=Regions
xlbl.recove_prev=Preventive recovery
xlbl.to_=to
xlbl.exportxls=Export data as Excel file
xlbl.date=Date
xlbl.debit=Debit
xlbl.credit=Credit
xlbl.solde_=Balance
xlbl.mo_ntant=Amount
xlbl.usd=USD
xlbl.CDF=CDF
xlbl.volume_dt=Volume of debt
xa_recouvr=To recover
xdeja_recov=Already recovered
xref_on_facture=Remittance on %s invoices
xclient=Customer
xnominal_recu_usd=Nominal amount received USD
xnominal_recu_cdf=Nominal amount received CDF
xnew_echeance=New due date
xdebtonly=Debts only
xcheance=Due date
ximputation=Imputation
xdistribution=Distribution
xapprov=Procurement
xadmin_fin=Admin & Finance
xproduct_ion=Production
xcompte=Account


#Storage
xentrepot=Warehouse
xstockage=Storage
xcreate_destockage= + Create destocking
xstock_in=Input into stock
xstock_out=Out of stock
xinventory=Global inventory holder
xrecev_stock=Reconstitute stock
xstockage_march=Storage of goods received
xtout_livrais=All deliveries
xfourniss=Supplier
xcontact=Contact
xadresse=Address
xmo_ntant_total=Total invoiced
xmo_ntant_paye=Paid amount
create_new_cat=Create new category
choose_cateory=Choose category
gorup_incateogey=Group in one category
xmontnat_restant=Remaining amount
xsuccess_saved=Successfully saved
xsuccess_update=Successfully updated
xarticle=Articles
xretour_stock=Return to stock
xdebut=Start
xfin=End
xadd_price=Add prices
xemmagasinage=Warehousing
methpppsaved=FEFO inventory method is set successfully
xappliquer_actual_price=Apply current prices
xrecquisitions=Requisitions
xlbl.stockage=Storage of goods
xlivr=Delivery :
xlivrz=Delivery
xnum_piece=Document number
subscomp=Subscriber companies
xreduction=Deduction (Optional)
xlibelle=Label
#-----
xstockage_de=Storage of :
xbtn.fill_last=Fill latest info
xlot_unique=Single batch
xlot_serie=Batch or series
xcol.lot=Batch number
xcout_achat_unitaire=Purchase cost per unit
xtotal=Total
xdate_expir_facult=Expiration date (optional)
xdate_expir_oblig=Expiry date
xlocalisation=Location
xpret_vent=Ready for sale
xprices=Selling price :
xlbl.ordercurency=Generate order in this currency

xtxtf.prompt.quantmin=Minimum Qty
xtxtf.prompt.quantmax=Maximum Qty
xtxtf.prompt.prixvun=Selling price per unit
xtxtf.equival.cdf=CDF equivalent
xlbl.items=Items
#--
xlbl.destockage_march=Stocking of goods
xcol.quantite=Quantity
xlbl.destination=Destination
xvalueur_stock=Stock value :
xqte_entree=Input quantity
xqte_sortie=Output quantity
xqte_restant=Remaining quantity
xalerte_stk=Stock alert
xvaleur_valeur=Value

xcritere_de_select=Selection criterion
xmonth=Month
xmontnat_restant_fac=Remaining amount (optional)
xrestera_depot=this will stay in the warehouse
xconfig_prices=Configure sales prices for this lot or

xadd_lot= + Add Batch
xnlot= %s Batches
xcot_total=Total cost
xadd_saleprice=Add sale price
xcot_unitr=Unit cost
xcomment=Comment
xfiche_stock=Stock sheet
xchoose_mes_ure=Choose a measure
xcons_moyn=Average cons: 
xcons_max=Maximum cons:
xdestock_vers=Store to store
xquant_disponible=Available quantity
xalveole=Alveole
xmag_destination=Destination point of sale
xdate_2_destockage=Date of unstorage 
xdate_exp_short=Exp. date:
xvaleur_stock_dispo=Available stock value

#Sale and requisition
xtooltip.vente_recquis=Sales & Requisitions
xpa_nier=Cart
xplus_option=More options
xPOS=POS
xrecquisit=Requisition
xinvent_mag=Store inventory
xhistory=History
xcol.date=Date
xretour_march_mag=Return of goods (%s)
xa_retirer=To withdraw
xin_peremption=Expiring
xen_alerte=Alert
xrech_scan_codebar=Search by scan codebar
xtooltip.sync_sales=Synchronize today's sales
xtooltip.afficher_table=Display data in a table
xtooltip.empty_cart=Empty cart
xbtn.pay_now=Pay now
xinformation_lot=Lot information
xajouuter_panier=Add to basket
xchoose_rapport_per=Choose report period
xexpire_from_today=From today until : 
#--
xid_fourniss=Supplier ID (optional)
xserach_supplier=Search supplier on cloud
xbtn.declasser=Unclassify
xmotif_declass=Cart downgrade reason
xbtn.add_recquis=Add a requisition
xlbl.historix=Sales history
addfavo=Add to favorites customers
xchbx.declasse_panier=Downgrade basket items
xlbl.prod_perem=Expiring products
xlbl.retour_march_depot=Return of goods to warehouse
xval_total_perem=Total expiring value: %s
xlbl.axces_soire=Accessories
xsaved_carts=Saved carts
xcartsavedsuccess=Cart saved successfully
xshowcartcontent=Show cart content
xcash_usd=Cash USD
xcash_cdf=Cash CDF
xdebts=Debts
xfilter_by_category=Filter by category
xtooltip.save_cart=Save cart and continue

#Agents
xage_nts=Agents
xsearch_on_cloud=Search on the cloud
xrole=Role
xbtn.eng_ager=Hire
xlbl.as=Like
xlbl.affected_at=Assign to:
xlbl.nom=Name
xlbl.pre_nom=First name
xlbl.phone=Phone
xlbl.post=Position
xlbl.comp_agnie=Company
xlbl.succursal=Branch
xlbl.entrep=Company
xlbl.payment_plan=Payment plan
xlbl.abonnment=Subscription
xlbl.detail=Details
xtxtf.prompt.nom_entr=Company name
xtxtf.propmt.numero_impot=Tax number
xtxtf.prompt.id_nat=National identification
xtxtf.vil_le=City
xcbx.gros_detail=Wholesale and retail trade
xcbx.gros=Wholesale trade
xcbx.detail=Detail trade
xcbx.indu_strie=Industrial
xcbx.service=Service
xtxtf.prompt.email=Mail address
xtxtf.prompt.website=Website (Optional)
xbtn.save_company=Register new company
xtooltip.update_logo=Modify company logo

#Parameters
xtooltip.param=Parameters
xlbl.accesibl=Accessibility parameters
xlbl.seconnect=Allow me to connect to my offline account without my login and password
xlbl.session_open=Keep my session open
xlbl.taux=Exchange rate parameter
xtxtf.equiv_taux=Enter the equivalent of one dollar in CDF
xlbl.parametre_sync=Synchronization parameter
xlbl.synchronisation=Synchronize
xlbl.print_param=Print parameter
xlbl.print_when_sale=Print invoice on sale registration
xlbl.tai_lle_police=Invoice Heading Font size
xlbl.level1=Size level 1
xlbl.level2=Size level 2
xlbl.level3=Size level 3
xlbl.param_meth=Inventory method parameter
xlbl.ppps=FEFO (First Expired First Out)
xlbl.fifo=FIFO (First In First Out)
xlbl.lifo=LIFO (Last In First Out)
xlbl.bas_fac_ture=Bottom text of invoice
xprompt.message_fact=Input the bottom invoice message 
xlbl.default_text=Thank you for choosing us
xtooltip.open_help=Open user manual
xcounter_param=Invoice numbering
xlbl.init_counter_bill_day=Initialize daily billing counter
xlbl.init_counter_bill_month=Initialize monthly billing counter
xlbl.init_counter_bill_year=Initialize billing counter every year
xlbl.init_counter_bill_trimestre=Initialize billing counter every quarter
xlbl.never_init_counter_bill_day=Never initialize billing counter 
xlbl.random_counter=Random bill counter

#others
cbx.fondator=Founder
cbx.manager=Manager
cbx.finance=Financial
cbx.magazin=Shopkeeper
cbx.vendor=Seller
cbx.magazinall=All-access storekeeper
cbx.cashall=All Access Cashier
cbx.vendorall=All Access Vendor
cbx.managerall=All access manager
txt.changeaffectag=Change an agent\u2019s affectaction
notfinish=Not finished!
error=Error
priv_msg=You don't have more privileges to run this action, contact your system admin
itemfound=item found
detailor=Retail customer
wholesaler=Wholesale customer
consumer=Consumer
subscriber=Subscribed customer
attach2bill=Attach to an invoice
delete=Delete
clean=Clean
sure2deleteclient=Are you sure you want to delete this client?
warning=Attention!
fillfield=Please complete all fields then start again
clientexist=The client with the same information seems to already exist
clientsaved=Client registered successfully
success=Success
noperish=Non-perishable
removefromlist=Remove from list
inventory=Inventory
xlowerprice=The sale price is lower or equal to the purchase cost of ( %s per unit )
xpriceinterval=Ambiguous price interval
xsave_recq4pos=Save also requisition
go2param4choice=Go to parameter to configure the method of your choice
fillnoptional=Please complete all non-optional fields first
fillmotif2class=Please also complete the observation (example: Reason for downgrading)
choosemez=Please select the measurement then continue
alertmess=Attention! this product has crossed the stock alert
alertyesmessage=By clicking YES, the stock will remain ZERO, because there is only %s %s left and you are asking %s %s
notsatisfyreq=Sorry! your request cannot be satisfied the stock is already out of stock
unstockingof=Unstocking of
unstocksaved=Unstock saved successfully!
nostockmsg=This product does not have valid stock or has not yet been stocked
pleaseselectmez=Please select a measurement for this product
subscriptionwarn=Your subscription is expiring soon, consider renewing it
xday=Days
pichaonly=Photos only
selectlogo=Select a logo for your business
newcompsaved=New company successfully created
compexist=The company with this identification already exists
networkerror=Internet connection problem!
moreprivmsg=You do not have the necessary privileges to perform this action
compupdated=Company successfully modified
comp.detailsnwhole=Commercial wholesaler and retailer
comp.detailor=Commercial retailer
comp.wholesaler=Wholesaler sales
comp.industry=Industrial
comp.service=Service
comp.spectacle=Show
login.userincorect=Incorrect user or password
login.compnotfound=Company with specified login not found, create using Android or web app at https://kazisafe.com
login.suspended=The suspended company or organization please contact the nearest Kazisafe customer service or contact the team via the Endeleya Corporation Facebook page or on support@kazisafe.com
login.engageinc=Personal account not found for the company provided
msgconf=Message configured successfully
inputaux=Enter the equivalent of one dollar in local currency CDF
ratesaved=The rate has been set successfully
rateerror=Enter numbers only
synconfigsaved=All the data have been reinitialized for synchronization
goodsoldmsg=Goods sold are neither returned nor exchanged
methppsaved=PPPS method configured successfully
methfifosaved=FIFO method configured successfully
methlifosaved=LIFO method configured successfully
choosemeth=Choose the inventory method for this product in setting, then try again
quantremn=The last quantity which remains is, %s %s for the current select batch %s do you want to add it anyway, to the cart?
quantexceed=You cannot add a quantity greater than what you have
stockalertok=The alert stock %s %s of this product in this lot %s has been exceeded \n do you want to add only to the requested quantity?
emptinesswarn=You cannot go lower than 1
stockfolio=Stock sheet
savestore=Save a storage
saveunstore=Save a clearance
showdetails=See details
confirmreturn=Confirm stock return
rtrsuccess=Return of stock confirmed successfully
confirmed=Confirmed
toreturncdf=Change to be repaid CDF
toreturnusd=Change to be refunded USD
clientname=Full name of client
phoneclient=Client phone
paymentmode=Payment mode
payment=Payment
invoice=Invoice
addclient=Add/select a client +
