# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
lbel.conx=Connexion
lbel.ident=ID
lbel.uzer=Utilisateur
lbel.pswd=Mot de passe
lbel.forget_pswd=Mot de passe oubli\u00e9 ?
lbel.newaccount=Cr\u00e9\u00e9r un nouveau compte
chbx.showpswd=Afficher le mot de passe
lbel.or_=ou
xlivrz=Livraison
lbel.slogan=Votre commerce en un lieu s\u00fbr
lbel.help=B\u00e9soin d'aide ?
txtfield.prompt.ident=Identification de l'entreprise
txtfield.prompt.uzer=T\u00e9l\u00e9phone utilisateur (+243xxx)
txtfield.prompt.pswd=Mot de passe
create_new_cat=Cr\u00e9\u00e9r une nouvelle categorie
xsuccess_saved=Enregistr\u00e9 avec succ\u00e8s
xsuccess_update=Modifi\u00e9 avec succ\u00e8s
choose_cateory=Choisir une cat\u00e9gorie
gorup_incateogey=Grouper dans une cat\u00e9rgorie
xgen_order=Generer un bon de commande
xmaincarency=Devise principale
xwarn_cli=Avertissement : CHER CLIENT S.V.P,VEUILLEZ VERIFIER VOS PRODUITS A LA RECEPTION PAS DES RECLAMATIONS APRES
#main
xtxtfield.prompt.rechr=R\u00e9chercher
xlbel.curen_tview=Tableau de bord
xtooltip.prodwi=Produits & Services
xtooltip.fina_nce=Tr\u00e9sorerie
xtooltip.entr_epot=Entrep\u00f4ts
xtooltip.vent_erecq=Ventes & R\u00e9cquisitions
xtooltip.ag_ents=G\u00e9rer les agents
xtooltip.rap_poro=Rapports
xtooltip.com_panie=Compagnie
xtooltip.param_ettre=Param\u00e8res
xtooltip.hel_p=Ouvrir le manuel
xlbel.loading=Chargement...
selectdeliv=Afficher ses livraisons
xtooltip.newdelivery=Nouvel approvisionement
xtooltip.newsupplier=Nouveau fournisseur
xtooltip.newitems=Nouvel article
xtooltip.fer_me=Fermer
xtooltip.redu_ire=Reduire
xtooltip.agran_dir=Agrandir
xlbel.depense_proport=Depense (%s%s) soit %s USD
xgraph.ti_tre=M\u00e9triques
xgraph.seri1_vente=Ventes
xgraph.seri2_depens=Co\u00fbt de r\u00e9vient
xgraph.seri3_marg=R\u00e9sultat
subscomp=Compagnies abonn\u00e9es
xmwezi_1=Janvier
xmwezi_2=Fevrier
xmwezi_3=Mars
xmwezi_4=Avril
xmwezi_5=Mai
xmwezi_6=Juin
xmwezi_7=Juillet
xmwezi_8=Ao\u00fbt
xmwezi_9=Septembre
xmwezi_10=Octobre
xmwezi_11=Novembre
xmwezi_12=D\u00e9cembre
xpie.ti_tre=Produit populaire
xlbel.ver_sion=Version
xlbel.majdispo=Mise \u00e0 jour disponible
xlbel.cre_ance=Volume de cr\u00e9ance
xlbel.tod_ay=Aujourd'hui

#Produits
xlbel.produx=Produits
xbtn.ajou_ter_produit=Ajouter un produit
xlink.tlcharger_xls=T\u00e9l\u00e9charger le fichier exemplaire .xls
xpas_de_selection=Pas de s\u00e9l\u00e9ction
xall_category=Toutes les categories
xcol.code_bar=Codebar
xaddingitem=Ajouter les articles
xcol.nom_produit=Nom du produit
xcol.mark=marque
xcol.modele=Modele/Forme
xcol.tail=Taille/Concentration
xflow=Couleur
xaction=Actions
xmes_ure=Mesures
xnon_mes_ure=Pas de mesure
xadd_mes_ure=Ajouter une mesure
xbtn.update=Modifier
updateliv=Modifier la livraison
clean=Effacer
xligne_par_pg=Ligne par page
xitems=%s El\u00e9ments
xtooltip.print_cb=Imprimer le codebar
xtooltip.import_xls=Importer les produits de puis un fichier excel
xtooltip.refresh=Actualiser les donnees
xtooltip.update=Modifier un element selectionne
xtooltip.delete=Supprimer un element selectionne
xtooltip.import_gros=Importer les produits avec les prix de gros et detail depuis Excel
xtooltip.import_detail=Importer les produits avec les prix de details
xtooltip.refresh=Actualiser les donnees
xlbl.new_prod=Nouveau produit
xlbl.categorie=Categorie
xchoose_category=Choisir une categorie
xtooltip.browse=Choisir une image depuis mon ordinateur
xtooltip.search=Rechercher l'image sur Google
xtxtf.prompt.cbar=Codebar du produit ou numero
xtxtf.prompt.nomp=Nom du produit
xtxtf.prompt.mark=Marque
xtxtf.prompt.model=Modele/Forme
xtxtf.prompt.tail=Taille/concentration(facultatif)
xtxtf.prompt.color=Couleur (facultatif)
xcbx.prompt.descrim=Description mesure
xcbx.prompt.unit_m=Nombre d'unite dans la mesure
xbtn.cancel=Annuler
xbtn.save=Enregistrer
xcbx.sample.pc=Piece
xcbx.sample.metre=Metre
xcbx.sample.tour=Tour
xcbx.sample.heure=Heure
xcbx.sample.bouteil=Bouteille
xcbx.sample.kg=Kg
xcbx.sample.plqt=Plaquette
xcbx.sample.plat=Plat
xcbx.sample.nuit=nuite
xlbl.mes_ure_prosel=Mesures pour le produit selectionne
xtxtf.prompt.descr=Description
txtf.prompt.qteum=Nombre d'unite dans la mesure
xbtn.add_mes_ure=Ajouter la mesure
xbtn.ok=OK
xbtn.yes=OUI
xbtn.no=NON
xbtn.next=Suivant >
xsite_destinat=Site destinataire
xsto_ckage_only=Stockage seulement
ximport_in_progress=Importation en cours...
xbtn.close=Fermer
xsave_recq4pos=Enregistrer aussi la recquisition
xpriceinterval=Interval de prix ambigu
xlowerprice=Le prix de vente propos\u00e9 est inferieur ou egal au co\u00fbt d'achat de ( %s l'unite )


#Tresorerie
xlbl.treso_rerie=Tr\u00e9sorerie
xlbl.cais_se=Caisse
xlbl.recov=R\u00e9couvrement
xlbl.depense=D\u00e9penses
xlbl.ecriture=Ecritures
xreference=R\u00e9f\u00e9rence
xlbl.encaiss=Encaissement
xlbl.decaiss=Decaissement
xtxtf.prompt.montant_usd=Montant USD
xtxtf.prompt.montant_cdf=Montant CDF
xcash_usd=Cash USD
xcash_cdf=Cash CDF
xdebts=Dettes

xtxtf.prompt.motif_trans=Motif de la transaction
xtxtf.prompt.observation=Observation (facultative)
xcol.observation=Observation
xregions=Regions
xlbl.recove_prev=R\u00e9couvrement pr\u00e9ventif
xlbl.to_=au
xlbl.exportxls=Exporter les donn\u00e9es en fichier Excel
xcol.date=Date
xlbl.date=Date
xlbl.debit=D\u00e9bit
xlbl.credit=Cr\u00e9dit
xlbl.solde_=Solde
xlbl.mo_ntant=Montant
xlbl.usd=USD
xlbl.CDF=CDF
xdebtonly=Dettes seulements
xlbl.volume_dt=Volume de dette
xa_recouvr=A recouvrer
xdeja_recov=D\u00e9j\u00e0 recouvr\u00e9e
xref_on_facture=R\u00e9parties sur %s factures
xclient=Client
xstatut=Etat
xbtn.mark_as_sold=Marqu\u00e9 comme vendu
xnominal_recu_usd=Montant nominal re\u00e7u USD
xnominal_recu_cdf=Montant nominal re\u00e7u CDF
xnew_echeance=Nouvelle \u00e9ch\u00e9ance
xcheance=Ech\u00e9ance
ximputation=Imputation
xdistribution=Distribution
xapprov=Approvisionnement
xadmin_fin=Admin & Finance
xproduct_ion=Production
xcompte=Compte


#Stockage
xentrepot=Entrep\u00f4t
xstockage=Stockage
xcreate_destockage= + Cr\u00e9\u00e9r un d\u00e9stockage
xstock_in=Entr\u00e9e en stock
xstock_out=Sortie en stock
xinventory=Invetaire global d\u00e9p\u00f4t
xrecev_stock=R\u00e9c\u00e9ptionner un stock
xstockage_march=Stockage des marchandises re\u00e7ues
xtout_livrais=Toutes les livraisons
xfourniss=Fournisseur
xcontact=Contact
xadresse=Adresse
xstock.empty=Stock en rupture
xlastdate=Dernier stock
xremainingstock=Stock restant
xmo_ntant_total=Total factur\u00e9
xmo_ntant_paye=Montant pay\u00e9
xmontnat_restant=Montant restant
xarticle=Articles
xretour_stock=Retour en stock
xdebut=D\u00e9but
xfin=Fin
xadd_price=Ajouter les prix de vente
xemmagasinage=Emmagasinage
xappliquer_actual_price=Appliquer les prix actuels
xrecquisitions=Recquisitions
xlbl.stockage=Stockage de marchandise
xlivr=Livraison :
xnum_piece=Num\u00e9ro piece justificative
xreduction=R\u00e9duction (Facultative)
xlibelle=Libelle
xshowcartcontent=Voir le contenu du panier
#-----
xstockage_de=Stockage de :
xbtn.fill_last=Remplire les derni\u00e8res infos
xlot_unique=Lot unique
xadd_saleprice=Ajouter le prix de vente
xlot_serie=Lot ou s\u00e9rie
xcol.lot=Num\u00e9ro Lot
xcout_achat_unitaire=Cout d'achat unitaire
xtotal=Total
xdate_expir_facult=Date d'expiration (facultatif)
xdate_expir_oblig=Date d'expiration
xlocalisation=Localisation
xpret_vent=Pr\u00eat \u00e0 la vente
xprix_achat=Prix d'achat
xcartsavedsuccess=Panier enregistre avec succes
xprices=Prix de vente :
xlbl.ordercurency=Utiliser la devise 
xtxtf.prompt.quantmin=Qt\u00e9 Minimum
xtxtf.prompt.quantmax=Qt\u00e9 Maximum
xtxtf.prompt.prixvun=Prix de vente unitaire
xtxtf.equival.cdf=Equivalent en CDF
xlbl.items=Items
#--
xlblstk.inrupt=Les produits en rupture de stock
xlbl.destockage_march=Destockage de marchandises
xcol.quantite=Quantit\u00e9
xlbl.destination=Destination
xvalueur_stock=Valeur de stock :
xqte_entree=Quantite entree
xqte_sortie=Quantite sortie
xqte_restant=Quantite restant
xalerte_stk=Stock d'alerte
xvaleur_valeur=Valeur

xcritere_de_select=Critere de selection
xmonth=Mois
xmontnat_restant_fac=Montant restant (facultative)
xrestera_depot=Ce stock restera au d\u00e9p\u00f4t ?
xconfig_prices=Configurer les prix de vente de ce lot ou

xadd_lot= + Ajouter lot
xnlot= %s Lots
xcot_total=Cout total
xcot_unitr=Cout unitaire
xcomment=Commentaire
xfiche_stock=Fiche de stock
xchoose_mes_ure=Choisir une mesure
xcons_moyn=Cons. Moyenne : 
xcons_max=Cons. Maximal :
xdestock_vers=Destocker vers magasin
xquant_disponible=Quantite disponible
xalveole=Alveole
xmag_destination=Point de vente destinataire
xdate_2_destockage=Date de destockage
xdate_exp_short=Exp. date:
xvaleur_stock_dispo=Valeur de stock disponible






#Vente et recqusition
xtooltip.vente_recquis=Ventes & R\u00e9cquisitions
xpa_nier=Panier
xplus_option=Plus d'option
xPOS=POS
xrecquisit=R\u00e9cquisition
xinvent_mag=Inventaire Point de vente
xhistory=Historique
xretour_march_mag=Retour de marchandise (%s)
xa_retirer=A r\u00e9tirer
xin_peremption=En voie de p\u00e9remption
xen_alerte=En alerte
addfavo=Add to favorites customers
xrech_scan_codebar=Rechercher par scan codebar
xtooltip.sync_sales=Synchroniser les ventes d'aujourd'hui
xexpire_from_today=Aujourd'hui jusqu'au
xtooltip.afficher_table=Afficher les donn\u00e9es dans un tableau
xtooltip.vider_cart=Vider le panier
xbtn.pay_now=Payer maintenant
xinformation_lot=Information du lot
xajouuter_panier=Ajouter au panier
xchoose_rapport_per=Choisir une p\u00e9riode du rapport
#--
xid_fourniss=IdNat fournisseur (facultatif)
xserach_supplier=R\u00e9chercher le fournisseur sur cloud
xbtn.declasser=D\u00e9classer
xmotif_declass=Motif de d\u00e9classement du panier
xbtn.add_recquis=Ajouter une r\u00e9cquisition
xlbl.historix=Historique des ventes
xchbx.declasse_panier=D\u00e9classer les \u00e9l\u00e9ments du panier
xlbl.prod_perem=Les produits en voie de p\u00e9remption
xlbl.retour_march_depot=Retour de marchandise au d\u00e9p\u00f4t
xval_total_perem=Valeur total en voie de p\u00e9remption : %s
xlbl.axces_soire=Acc\u00e8ssoires
xsaved_carts=Paniers enregistr\u00e9s(coming soon)
xfilter_by_category=Filtrer par categorie
xtooltip.save_cart=Enregistrer le panier et continuer

#Agents
xage_nts=Agents
xsearch_on_cloud=Rechercher sur le cloud
xrole=Role
xbtn.eng_ager=Engager
xlbl.as=Comme
xlbl.affected_at=Affecter \u00e0:
xlbl.nom=Nom
xlbl.pre_nom=Prenom
xlbl.phone=T\u00e9l\u00e9phone
xlbl.post=Poste
xlbl.comp_agnie=Compagnie
xlbl.succursal=Succursale
xlbl.entrep=Entreprise
xlbl.payment_plan=Plan de paiement
xlbl.abonnment=Abonnement
xlbl.detail=D\u00e9tails
xtxtf.prompt.nom_entr=Nom de l'entreprise
xtxtf.propmt.numero_impot=Num\u00e9ro d'imp\u00f4t
xtxtf.prompt.id_nat=Identification nationale
xtxtf.vil_le=Ville
xcbx.gros_detail=Commerce gros et detail
xcbx.gros=Commerce gros
xcbx.detail=Commerce detail
xcbx.indu_strie=Industriel
xcbx.service=Service
xtxtf.prompt.email=Adresse mail
xtxtf.prompt.website=Site web (Facultatif)
xbtn.save_company=Enregistrer une nouvelle entite
xtooltip.update_logo=Modifier le logo de l'entreprise

#Parametres
xtooltip.param=Param\u00e8tres
xlbl.accesibl=Param\u00e8tres d'accessibilite
xlbl.seconnect=Permettre de se connecter a mon compte offline sans mes identifiants
xlbl.session_open=Garder ma session ouverte
xlbl.taux=Param\u00e8tre de taux de change
xtxtf.equiv_taux=Entrer l'equivalent d'un dollar en CDF
xlbl.parametre_sync=Param\u00e8tre de synchronisation
xlbl.synchronisation=Synchroniser
xlbl.print_param=Param\u00e8tre d'impression
xlbl.print_when_sale=Imprimer la facture lors de l'enregistrement de la vente
xlbl.tai_lle_police=Taille de la police d'entete
xlbl.level1=Taille niveau 1
xlbl.level2=Taille niveau 2
xlbl.level3=Taille niveau 3
xlbl.param_meth=Param\u00e8tre de methode d'inventaire
xlbl.ppps=PPPS (Pr\u00e9mier Perim\u00e9 Pr\u00e9mier Sortie)
xlbl.fifo=FIFO (First In First Out)
xlbl.lifo=LIFO (Last In First Out)
xlbl.bas_fac_ture=Texte de bas de la facture
xlbl.default_text=Merci de nous avoir choisi
xtooltip.open_help=Ouvrir le manuel d'utilisation
xprompt.message_fact=Entrer le message de bas de la facture
xcounter_param=Num\u00e9rotation de la facture
xlbl.init_counter_bill_day=Initialiser le compteur de facturation chaque jour
xlbl.init_counter_bill_month=Initialiser le compteur de facturation chaque mois
xlbl.init_counter_bill_year=Initialiser le compteur de facturation chaque chaque ann\u00e9e
xlbl.init_counter_bill_trimestre=Initialiser le compteur de facturation chaque trimestre
xlbl.never_init_counter_bill_day=Ne jamais initialiser le compteur de facturation 
xlbl.random_counter=Compteur de facture al\u00e9atoire

#Others
cbx.fondator=Fondateur
cbx.manager=G\u00e9rant
cbx.finance=Financier
cbx.magazin=Magasinier
cbx.vendor=Vendeur
cbx.magazinall=Magasinier tout acces
cbx.cashall=Caissier tout acces
cbx.vendorall=Vendeur tout acces
xall=Selectionner tout
cbx.managerall=G\u00e9rant tout acces
txt.changeaffectag=Changer l'affectaction d'un agent
notfinish=Non termin\u00e9!
error=Erreur
priv_msg=Vous n'avez pas assez de privileges pour executer cette action, contactez votre admin system
itemfound=\u00e9l\u00e9ment trouv\u00e9s
detailor=Client d\u00e9taillant
wholesaler=Client grossiste
consumer=Consommateur
subscriber=Client abonn\u00e9
attach2bill=Attacher \u00e0 une facture
delete=Supprimer
sure2deleteclient=Etes vous s\u00fbr de vouloir supprimer ce client ?
warning=Attention!
fillfield=Veuillez completer tout les champs puis recommencer
clientexist=Le client avec les m\u00eames infos semble exister d\u00e9j\u00e0
clientsaved=Client enregistr\u00e9 avec succ\u00e8s
success=Succ\u00e8s
noperish=Non p\u00e9rissable
removefromlist=Enlever de la liste
inventory=Inventaire
go2param4choice=Aller dans parametre pour configurer la methode de votre choix
fillnoptional=Veuillez completer d'abord tous les champs non facultatif
fillmotif2class=Veuillez completer aussi l'observation (exemple: Motif de declassement)
choosemez=Veuillez selectionner la mesure puis continuer
alertmess=Attention! ce produit franchi le stock d'alerte
alertyesmessage=En cliquant sur OUI, le stock restera ZERO,car il ne reste que %s %s  et vous et vous demandez %s %s
notsatisfyreq=D\u00e9sol\u00e9! votre demande ne pourra pas \u00eatre satisfait le stock est d\u00e9j\u00e0 epuis\u00e9 
unstockingof=Destockage du 
unstocksaved=Destockage enregist\u00e9 avec succ\u00e8s!
nostockmsg=Ce produit n'a pas de stock valide ou n'a pas encore \u00e9t\u00e9 approvisionn\u00e9
pleaseselectmez=Veuillez s\u00e9l\u00e9ctinner une mesure pour ce produit
subscriptionwarn=Votre abonnement expire bient\u00f4t, pensez \u00e0 le renouveller
xday=Jours
pichaonly=Photos seulements
selectlogo=S\u00e9l\u00e9ctionner un logo pour votre entreprise
newcompsaved=Nouvelle entreprise cr\u00e9\u00e9e avec succ\u00e8s
compexist=L'entreprise ayant cette identification existe d\u00e9j\u00e0
networkerror=Probleme de connection internet!
moreprivmsg=Vous n'avez pas des privil\u00e8ges n\u00e9c\u00e9ssaire pour executer cette action
compupdated=Entreprise modifi\u00e9e avec succ\u00e8s
comp.detailsnwhole=Commerciale grossiste et detaillant
comp.detailor=Commerciale detaillant
comp.wholesaler=Commerciale grossiste
comp.industry=Industrielle
comp.service=Service
comp.spectacle=Spectacle
login.userincorect=Utilisateur ou mot de passe incorrecte
login.compnotfound=L'entreprise ayant l'identifiant sp\u00e9cifi\u00e9e introuvable, cr\u00e9\u00e9r en utilisant l'application Android ou web sur https://kazisafe.com
login.suspended=L'entreprise ou organisation suspendue veuillez, contacter le service client Kazisafe le plus proche ou contactez l'equipe via la page facebook Endeleya Corporation ou sur support@kazisafe.com
login.engageinc=Compte personnel introuvable pour l'entreprise fournie
msgconf=Message configur\u00e9 avec succ\u00e8s
inputaux=Entrer l'equivalent d'un dollar en monnaie locale CDF
ratesaved=Le taux a \u00e9t\u00e9 parametr\u00e9 avec succ\u00e8s
rateerror=Entrer uniquement les chiffres
synconfigsaved=Les donn\u00e9es ont \u00e9t\u00e9 reinitialis\u00e9e pour la synchronisation
goodsoldmsg=Les marchandises vendues ne sont ni reprises ni echangees
methpppsaved=La methode PPPS configuree avec succes
methfifosaved=La methode FIFO configuree avec succes
methlifosaved=La methode LIFO configuree avec succes
choosemeth=Choisir la m\u00e9thode d'inventaire de ce produit dans param\u00e8tre, puis r\u00e9essayer
quantremn=Il ne vous reste que, %s %s pour ce lot %s voulez vous les ajouter qu'a meme ?
quantexceed=Vous ne pouvez pas ajouter une quantite superieur que celle que vous disposez
stockalertok=Le stock d'alerte %s %s de ce produit dans ce lot %s a \u00e9t\u00e9 franchi \n voulez vous ajouter qu'a m\u00eame la quantit\u00e9 demand\u00e9e ?
emptinesswarn=Vous ne pouvez pas aller au plus bas que 1
stockfolio=Fiche de stock
savestore=Enregistrer un stockage
saveunstore=Enregistrer un destockage
showdetails=Voir les details
confirmreturn=Confirmer le retour de stock
rtrsuccess=Retour de stock confirme avec succes
confirmed=Confirm\u00e9
toreturncdf=Change \u00e0 rembourser CDF
toreturnusd=Change \u00e0 rembourser USD
clientname=Nom complet du client
phoneclient=Telephone du client
paymentmode=Mode de paiement
payment=Paiement
invoice=Facture
addclient=Ajouter/selectionner un client +














