# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

lbel.conx=Bokangami
lbel.ident=ID
lbel.uzer=Mosaleli
lbel.pswd=Mot ya nzela
lbel.forget_pswd=Obosani mot ya nzela?
lbel.newaccount=Sal\u00e1 k\u0254nti ya sika
lbel.or_=to
lbel.slogan=Mombongo na yo na esika ya libateli
txtfield.prompt.ident=Boyebisi ya kompanyi
txtfield.prompt.uzer=Telephone ya mosaleli (+243xxx)
txtfield.prompt.pswd=Mot ya nzela
#main
txtfield.prompt.rechr=Bolukiluki
lbel.currentview=Etanda ya bopanzi sango
tooltip.prodwi=Biloko & Misala
tooltip.fina_nce=Mosolo ya mbongo
tooltip.entr_epot=Ba entrep\u00f4ts
tooltip.vent_erecq=Boteki & Bosenga
tooltip.ag_ents=Kokamba ba Agents
tooltip.rap_poro=Malapolo
tooltip.com_panie=Ebongiseli
tooltip.param_ettre=Ba param\u00e8tres
tooltip.hel_p = Fungola buku ya malako
graph.ti_tre=Ba m\u00e9triques
graph.seri1_sale=Bot\u025bki
graph.seri2_depens = Ba depanse
graph.seri3_marg=Ba Marge
mwezi_1=Mokolo ya yambo
mwezi_2=Mbula ya mibale
mwezi_3=Mars
mwezi_4=Mokolo ya minei
mwezi_5=Mai
mwezi_6=Mokolo ya motoba
mwezi_7=Mokolo ya nsambo
mwezi_8=Ao\u00fbt ya sanza ya mwambe
mwezi_9=S\u025bt\u025b\u0301mb\u025b
mwezi_10=Mokolo ya zomi
mwezi_11=Makolo ya zomi na moko
mwezi_12=Mokolo ya zomi na mibale
pie.ti_tre=Eloko oyo bato mingi balingaka
lbel.ver_sion=Bobongoli
lbel.majdispo=Mikolo ya sika ezali
lbel.cre_ance=Volume ya bokeli
lbel.tod_ay=Lelo oyo
lbel.sol_des=Ba solde ya mbongo