# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

lbel.conx = Kwihuza
lbel.ident = ID
lbel.uzer = Umukoresha
lbel.pswd = Ijambobanga
lbel.forget_pswd = Wibagiwe ijambo ryibanga?
lbel.newaccount = Kurema konti nshya
lbel.or_ = cyangwa
lbel.slogan = Ubucuruzi bwawe ahantu hizewe
txtfield.prompt.ident = Kuranga sosiyete
txtfield.prompt.uzer = Terefone y'abakoresha (+ 243xxx)
txtfield.prompt.pswd = Ijambobanga
lbel.help = Ukeneye ubufasha?
#main
txtfield.prompt.rechr = Ubushakashatsi
lbel.currentview = Ikibaho
tooltip.prodwi = Ibicuruzwa & Serivisi
ibikoresho.fina_nce = Amafaranga
ibikoresho.entr_epot = Ububiko
ibikoresho.vent_erecq = Igurisha & Ibisabwa
tooltip.ag_ents = Gucunga abakozi
tooltip.rap_poro = Raporo
ibikoresho.com_panie = Isosiyete
ibikoresho.param_ettre = Ibipimo
ibikoresho.hel_p = Gufungura igitabo
igishushanyo.ti_tre = Ibipimo
igishushanyo.seri1_sale = Igurisha
igishushanyo.seri2_depens = Amafaranga
igishushanyo.seri3_marg = Margin
mwezi_1 = Mutarama
mwezi_2 = Gashyantare
mwezi_3 = Mars
mwezi_4 = Mata
mwezi_5 = Gicurasi
mwezi_6 = Kamena
mwezi_7 = Nyakanga
mwezi_8 = Kanama
mwezi_9 = Nzeri
mwezi_10 = Ukwakira
mwezi_11 = Ugushyingo
mwezi_12 = Ukuboza
pie.ti_tre = Ibicuruzwa bizwi
lbel.ver_sion = verisiyo
lbel.majdispo = Kuvugurura birahari
lbel.cre_ance = Umubumbe wo guhanga
lbel.tod_ay = Uyu munsi
lbel.sol_des = Amafaranga asigaye
