# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

lbel.conx=Muunganisho
lbel.ident=ID
lbel.uzer=Mtumiaji
lbel.pswd=Nenosiri
lbel.forget_pswd=Umesahau neno la siri?
lbel.newaccount=Fungua akaunti mpya
lbel.or_=au
lbel.slogan=Biashara yako mahali salama
lbel.help=Hadja ya msaada ?
txtfield.prompt.ident=Kitambulisho cha kampuni
txtfield.prompt.uzer=Simu ya mtumiaji (+243xxx)
txtfield.prompt.pswd=Nenosiri


#main
txtfield.prompt.rechr=Tafiti
lbel.currentview=Dashibodi
tooltip.prodwi=Bidhaa na Huduma
tooltip.fina_nce=Fedha
tooltip.entr_epot=Maghala
tooltip.vent_erecq=Mauzo na Mahitaji
tooltip.ag_ents=Dhibiti Mawakala
tooltip.rap_poro=Ripoti
tooltip.com_panie=Kampuni
tooltip.param_ettre=Vigezo
tooltip.hel_p = Fungua mwongozo
graph.ti_tre=Metriki
graph.seri1_sale=Mauzo
graph.seri2_depens = Gharama
graph.seri3_marg=Pembezoni
mwezi_1=Januari
mwezi_2=Februari
mwezi_3=Mars
mwezi_4=Aprili
mwezi_5=Mei
mwezi_6=Juni
mwezi_7=Julai
mwezi_8=Agosti
mwezi_9=Septemba
mwezi_10=Oktoba
mwezi_11=Novemba
mwezi_12=Desemba
pie.ti_tre=Bidhaa Maarufu
lbel.ver_sion=Toleo
lbel.majdispo=Sasisho linapatikana
lbel.cre_ance=Kiasi cha Ubunifu
lbel.tod_ay=Leo
lbel.sol_des=Salio la Fedha Taslimu
